apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:mhzfHcMx4z+vUvv2RewbhhHUNq2Ne2468GNfo0FjVuJOiLGNyQxkdmsRLraXS8mJdKSRvEPifrJYmGlYmo2KRr0FZFLf6VN6DMTEmG6EEjQlrCNYfdDph3/btXwfmHho//0UK1YQnYLTe+e9Jumd+3B2v1D8owc1RgSJH8nc5pT05sf+WHTqs9ICSwwThAfVDq/tf8YRTMVADZ5oomlXd5NF60vpYEdLFeP1hX+csx/IhMJGL5HYytOhLYbaP+vN13M1dDjMThg1x6moi8N98sbslolE/4bICD/blFgH9gxLeTURuZnCpMq4gA8=,iv:xerAvbPWAfe5f6sRZyJ81ahSuaUf6QbhEAMkrjy7Ai0=,tag:w3E3x+1YFdZ1zcUZ6Jr+Uw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: abs-tunnel-secret
sops:
    age:
        - recipient: age1y9npvwqupmnwkvs8deuxu82gdh4a6z0upys5she0g3s06rsfsunsk72lld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNGx3d2x0TkxRMTA3amtS
            TzIxcDY1Z1hBKzVaQzlPNkNyY0czZ2orZXlRClg5WUtFcWNOb3hReVpVNWdPMkU3
            aE1mSXZJc1BSUEJvYnhoMENRN3N5bFkKLS0tIGJjbUZ1NVpBUndCa2srQTUvRzdB
            UXBFTmxKRmV5WG9iT1FQS0QzdjdaZmMKTz/P+bb+bE7k5C7w8h2UmWJi8pm0qmjw
            wX/XrrbvWWJOVI+Fvazo/xGdkAtFyPW5VoNbSXSWNHG7+cLDMSOXMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T20:32:49Z"
    mac: ENC[AES256_GCM,data:MAOlAYeZWjM/iU7h4g4Xzl36JMazjYli7far1ASOnHQj+CQj7cs4Dg5USK3Q5TtteKBq0jDkSL8yjIv3kajAkmHiAjiOO8KwkJPQ8IJ462f9vu4jZN/Dh7Lgq6jWzCLSrfx7PaQXjqdsT1xP58jxb8ZIkMPjLurJnf6HjRmt+XU=,iv:g8AOvyFPNGts/bnZfPKcK/enn2CSbJGDs0R/xPGSDus=,tag:iz5C5mq5Sd2Mo5Y5EGRw9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
