apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:yCe1X1+BNa4=,iv:ktDP55POtbVakhpgRRHHWNpyh6XnWigl0x/et6nb7sU=,tag:bbwqVumyjaeeZPgYFSkJ2g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:QVqYLK3xZK6Q79Wf,iv:Awb0/yoyNPOLoV/VjHueQKm5sAKhwdG9y0L6eYivrkA=,tag:ALNP4vPX22URVZJyRAb+pw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-secret
sops:
    age:
        - recipient: age1y9npvwqupmnwkvs8deuxu82gdh4a6z0upys5she0g3s06rsfsunsk72lld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1JwMDF3V3Q3V2dlWEJC
            TjZYa21XOVE1d01uK21yQWM4NHlZTWUrelQwCnVqczN0WElCS3R5aHlHQzdKbDVZ
            SVVtb1JuMmxpOXRsOHBpM0pScW1DVUUKLS0tIHlycEZUbHZRajdka3ZMM05sVk0v
            VEdsNjBKMm50bWFTVHR6cTcvbmhJanMKioWQVvmruRyDJfsF+8QFUSbrfHZ5E4qx
            d7iFFtXUQAgiWx2G0DcglDEdGc5VEFHuuoTwJSQlALMguGI0hT8Q6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T16:28:08Z"
    mac: ENC[AES256_GCM,data:6hmqagg7/knMfZm818RBrJ9KoCzD1GimVk+dbS9TDwOJu1za+9uVWVJBvB0WYpaBh0Tyhm1MXwAHmlsSYQRZmTMIsbDCrGcL+sXY83PUp1wZP7V6QN8ALqIqsaSfLM3bwFhfwwLHnWvIkJc4ps4hwiIDsVJQz27T1BtnJZt9bQI=,iv:T0VI/ALG07Kx5KxsVaEqhUsfAnlKr5WRyP8UUTw2mPs=,tag:5wX589C+WuIkD72DZneb0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
